### ISSUE TITLE
Cannot change page in Alloy app during Scenario

### ISSUE THREAD

**Issue by janvandenberg** [appersonlabs/TiCalabash#23]
First of all, thanks very much for taking the effort to write this tool. 

We really want to start using it for a new project. It works great as long if I don't change the window and stay on the index view. But when I change page e.g:

    var startController =    Alloy.createController( "start" );
    var startWindow =        startController.getView();
    startWindow.open()

Then I get this error: couldn't find module alloy/controllers/start 

I think I'm just forgetting something obvious, but I can't see what it is. Building the same code works. I've tried running the test_harness example but that (also) doesn't work on my machine.

I'm using these versions: alloy 1.5.1, titanium 3.4.1. calabash-ios 0.12.0. I'm trying to test an iOS (alloy) app in the Simulator.

Any help would be greatly appreciated. 

Regard,
Jan van den Berg

**Comment by Sophrinix** [comment]
Interesting. I tend to use my fork of the Alloy Fugitive code to smoke test TiCalabash.
https://github.com/codexlabs/alloy_fugitive

It opens a controller in at least one example. 
I'll test this out in a few minutes.

**Comment by janvandenberg** [comment]
Strangely enough I do see some page transactions for the alloy_fugitive test run. But all scenario quit because of runtime errors like this:

 `touch could not find view: 'view marked:'Blain Hamon'', args: {:query=>"view marked:'Blain Hamon'"} (RuntimeError) `

I don't know if this is related to the issues I'm having.

**Comment by Sophrinix** [comment]
It almost sounds like you need to do a clean and try again. I know that sounds stupid, but the more I look at the error you are having the more I suspect that.

try deleting the contents of the build directory and the resources directory.

**Comment by janvandenberg** [comment]
This is what I've done (to the alloy_fugitive app)
`rm -rf ./build/*`
`rm -rf ./Resources/*`
`ti build -b -p ios && ti calabash --platform=iphone`

Still no working test scenario's :-(

**Comment by janvandenberg** [comment]
But if you smoke test TiCalabash with the latest Titanium CLI's you don't get any issues?
Maybe redundant but I'm also using the latest ruby version e.g. ruby 2.2.0p0

**Comment by janvandenberg** [comment]
Okay took me a couple of hours but updating cucumber did the trick for me. :-)
