### ISSUE TITLE
Error while installing TiCalabash

### ISSUE THREAD

**Issue by narendraraorane** [appersonlabs/TiCalabash#27]
Hi,

While installing ticalabash through npm
sudo npm install -g ticalabash
I am getting the below error,

[ERROR] Invalid key "/usr/local/lib/node_modules/ticalabash/plugin"
After that if I tried to run ti calabash --platform=ios command it is giving me the below error.
[ERROR] "calabash" is an unrecognised command.

I tried remove sudo and giving access to lib directory as suggested in README.

Please find below my configuration.
OS - Mac OS X (10.10.2)
ticalabash - 1.1.2
Ti SDK - 4.0.0.GA
Ti CLI Version - 4.0.0

Thanks,
Narendra Raorane.

**Comment by Sophrinix** [comment]
try reinstalling ticalabash again. I just did an update ~6 days ago.

**Comment by narendraraorane** [comment]
Thanks Andrew. I will do that.


Really appreciate your help.

Sent from Yahoo Mail on Android

**Comment by narendraraorane** [comment]
@Sophrinix It's not working. I am getting the same error as above. Ruby version on my mac is 2.0.0p481.

Thanks,
Narendra Raorane

**Comment by Sophrinix** [comment]
can you copy and paste your terminal buffer?

**Comment by narendraraorane** [comment]
Here you go...

Narendras-MacBook-Pro:Documents narendraraorane$ npm install -g ticalabash
/
> ticalabash@1.4.0 postinstall /usr/local/lib/node_modules/ticalabash
> node install

Installing titanium stuff...
--- Installing Build Command(s) ---
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
Password:
Successfully installed bundler-1.10.4
1 gem installed
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using CFPropertyList 2.3.1
Using awesome_print 1.6.1
Using builder 3.2.2
Using bundler 1.10.4
Using diff-lcs 1.2.5
Using multi_json 1.11.1
Using gherkin 2.12.2
Using multi_test 0.1.2
Using cucumber 1.3.19
Using escape 0.0.4
Using httpclient 2.6.0.1
Using json 1.8.3
Using retriable 1.4.1
Using rubyzip 1.1.7
Using slowhandcuke 0.0.3
Using calabash-android 0.5.10
Using calabash-common 0.0.1
Using edn 1.0.7
Using geocoder 1.2.9 (was 1.2.8)
Using thor 0.19.1
Using run_loop 1.3.3
Installing rack 1.6.4 (was 1.6.1)
Using rack-protection 1.5.3
Using tilt 2.0.1
Using sinatra 1.4.6
Using sim_launcher 0.4.13
Using calabash-cucumber 0.14.3
Bundle updated!
Titanium Command-Line Interface, CLI version 4.0.0, Titanium SDK version 4.0.0.GA
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

[ERROR] Invalid key "/usr/local/lib/node_modules/ticalabash/plugin"

Titanium CLI command calabash installed.
ticalabash@1.4.0 /usr/local/lib/node_modules/ticalabash
├── pkginfo@0.3.0
├── underscore@1.8.3
├── tiapp@0.0.2 (underscore@1.5.2, xml2js@0.2.8)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── xml2js@0.4.9 (sax@0.6.1, xmlbuilder@2.6.4)
└── node-appc@0.2.26 (diff@1.0.8, sprintf@0.1.5, colors@0.6.2, xmldom@0.1.19, node-uuid@1.4.3, async@0.9.2, wrench@1.5.8, semver@3.0.1, adm-zip@0.4.7, temp@0.8.3, optimist@0.6.1, request@2.40.0, uglify-js@2.4.23)

Thanks,
Narendra

**Comment by Sophrinix** [comment]
when you type titanium on the command prompt, do you see calabash as a command? 
It looks like it "worked". 

I will look into this error invalid key error message.

**Comment by narendraraorane** [comment]
Thanks for your suggestion. I tried that one also but it didn't work for me. Below is the log,

Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ titanium calabash
Titanium Command-Line Interface, CLI version 4.0.0, Titanium SDK version 4.0.0.GA
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

[ERROR] "calabash" is an unrecognized command.

Run 'titanium help' for available commands.

Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ appc calabash
Appcelerator Command-Line Interface, version 4.0.2
Copyright (c) 2014-2015, Appcelerator, Inc.  All Rights Reserved.

Invalid command calabash. Use appc help for usage.
Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ appc calabash -p ios
Appcelerator Command-Line Interface, version 4.0.2
Copyright (c) 2014-2015, Appcelerator, Inc.  All Rights Reserved.

Invalid command calabash. Use appc help for usage.
Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ titanium help
Titanium Command-Line Interface, CLI version 4.0.0, Titanium SDK version 4.0.0.GA
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

Usage: titanium <command> [options]

Commands:
   build     builds a project
   clean     removes previous build directories
   config    get and set config options
   create    creates a new mobile application
   help      displays this help screen
   info      display development environment information
   module    displays installed Titanium modules
   plugin    displays installed Titanium CLI plugins
   project   get and set tiapp.xml settings
   sdk       manages installed Titanium SDKs
   setup     sets up the Titanium CLI
 
Global Flags:
   --no-banner          disable Titanium version banner 
   --no-colors          disable colors 
   --no-progress-bars   disable progress bars 
   --no-prompt          disable interactive prompting 
   -h, --help           displays help 
   -q, --quiet          suppress all output 
   -v, --version        displays the current version 
 
Global Options:
   --config <json>        serialized JSON string to mix into CLI config
   --config-file <file>   path to CLI config file  [default:
                          /Users/narendraraorane/.titanium/config.json]
   -s, --sdk <version>    Titanium SDK version to use to bootstrap SDK-level commands and parse the
                          tiapp.xml; actual Titanium SDK used determined by <sdk-version> in the
                          tiapp.xml  [default: latest]
 
Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ 

Regards,
Narendra Raorane

**Comment by shodanuk** [comment]
A minor point but if you're trying to execute Titanium commands via appc, the correct syntax is: 

```app ti xxxx```

where xxxx is the Titanium command you want to run. So you could try:

```appc ti calabash -p ios```

**Comment by narendraraorane** [comment]
@shodanuk Thanks for bringing in notice. I tried your suggested command (appc ti calabash -p ios) but no luck. Below is the error that I am getting,

Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ appc ti calabash -p ios
Appcelerator Command-Line Interface, version 4.0.2
Copyright (c) 2014-2015, Appcelerator, Inc.  All Rights Reserved.

[ERROR] "calabash" is an unrecognized command.

Run 'titanium help' for available commands.

Narendras-MacBook-Pro:TiCalabashTest narendraraorane$ appc ti calabash --platform=[ios]
Appcelerator Command-Line Interface, version 4.0.2
Copyright (c) 2014-2015, Appcelerator, Inc.  All Rights Reserved.

[ERROR] "calabash" is an unrecognized command.

Run 'titanium help' for available commands.

Regards,
Narendra Raorane

**Comment by narendraraorane** [comment]
It's working with Appc SDK 4.1.0.GA and CLI 4.1.2
