### ISSUE TITLE
Error: spawn ENOENT during "ti calabash -p android"

### ISSUE THREAD

**Issue by zozo4kin** [appersonlabs/TiCalabash#32]
Perform "ti calabash -p android". (TiSDK of android project in tiapp.xml = 3.5.1. Appc = 5.02. Ti = 5.0.5)

Project built successfully! But after this I get error.

```
[INFO]  Writing build manifest: /Users/zozo4kin/Appcelerator_Studio_Workspace/mobile-camera-uploader/build/android/build-manifest.json
[INFO]  Performed build only, skipping installing of the application
[INFO]  Project built successfully in 17s 749ms

Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by lawjeremy** [comment]
Were you able to work this out? I am seeing the same thing.

**Comment by alvesl** [comment]
I have that exactly, but for iOS.

Any ideas?

**Comment by zozo4kin** [comment]
I've fixed it! Look at this file: https://github.com/appersonlabs/TiCalabash/blob/master/Gemfile. You have to install this gems. It solved this problem for me.
