### ISSUE TITLE
Make it compatible with AppC

### ISSUE THREAD

**Issue by alvesl** [appersonlabs/TiCalabash#33]
Hello!
Any chance to make it compatible with appc, now that Ti is heavily discouraged?

Should it work with latest SDKs? 

I get:
```
Error: spawn calabash-ios ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

When trying to compile...

**Comment by mattapperson** [comment]
Not at this time. We use the OSS SDK. If someone wants to create a PR to work with Appc then thats fine, but we have no plans to do that ourselves

**Comment by alvesl** [comment]
I understand, thanks a lot! 

What about the compiling error? Any help there would be greatly appreciated!

**Comment by alvesl** [comment]
Actually, if I clean the project error goes away, but then all I get is this line:

```
➜  ComponentsExample  ti calabash -p ios
iphone:  /Users/la/Documents/Appcelerator_Studio_Workspace/ComponentsExample/build/iphone
```
